spring:
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customers/**
      - id: ACCOUNT-SERVICE
        uri: lb://ACCOUNT-SERVICE
        predicates:
        - Path=/accounts/**
